name: Build and Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t bot_war .

      - name: Run Docker container (temporary)
        run: |
          docker run -d -p 4000:4000 --name bot_war_container bot_war
          docker ps

      - name: Trigger Render Deploy
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d28u9amr433s73c005fg?key=q-61FflA9Kk"
